import Head from "next/head";
import { useEffect, useState } from "react";

type Lesson = {
  lessonTitle: string;
  isComplete: boolean;
};

type Chapter = {
  chapter: string;
  chapterOrder: number;
  lessons: Lesson[];
};

type ChaptersData = Chapter[];

export default function Home() {
  const [chapters, setChapters] = useState<ChaptersData>([]);
  const createTest = async () => {
    const res = await fetch("/api/chapter/get");
    const data = await res.json();

    setChapters(data.data);
  };

  useEffect(() => {
    createTest();
  }, []);

  console.log(chapters);
  return (
    <div>
      <Head>
        <title>Progress Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-6">
        {chapters.map(({ chapter, chapterOrder, lessons }) => (
          <div key={chapter}>
            <h2 className="text-2xl font-bold">
              {chapterOrder}. {chapter}
            </h2>

            {lessons.map(({ lessonTitle, isComplete }) => (
              <div key={lessonTitle} className="flex gap-2 ml-6">
                <input type="checkbox" checked={isComplete} />
                <h4>{lessonTitle}</h4>
              </div>
            ))}
          </div>
        ))}
      </main>
    </div>
  );
}
